#! /bin/bash
#----------------------------------------------------------------
# Nombre    :  carga_parametros_V2.3.sh
# Creado por: ./a_nc_V2.3.sh     Run_date  : # 2018/08/16 18:07
# Branch    :  Idea_loca_3

# Directorio Origen:  /home/badubko/Documents/Ordena_Fotos_Cel/Develop
# IN_FILE :  datos_parametros_V2.3.sh
#----------------------------------------------------------------
# Warning   : DO NOT EDIT THIS FILE !!!
#----------------------------------------------------------------
carga_parametros () {

# Variables incluidas:
REPOS_A_CONS=(1 0)

REGEN_LISTA_FILES_REP[1]=TRUE						# <-----  <MODIFICABLE>

REGEN_LISTA_FILES_REP[0]=TRUE						# <-----  <MODIFICABLE>

SOLO_REGEN_LISTA_FILES_REP[1]="FALSE"					# <-----  <MODIFICABLE>

SOLO_REGEN_LISTA_FILES_REP[0]="FALSE"					# <-----  <MODIFICABLE>

REPOSITORIO[0]=/media/CGate/badubko/Photos/Dir0			# <-----  <MODIFICABLE>

REPOSITORIO[1]=/media/CGate/public/Photos/Dir1			# <-----  <MODIFICABLE>

PREFIJO[0]="YXDir0XY" 

PREFIJO[1]="YXDir1XY"

LISTA_DIRS[0]=""

LISTA_DIRS[1]=""

WORK_DIR=~/Work_Dir_Ordena_Fotos_Cel   						# <-----  <MODIFICABLE>

LISTA_FILES_REP[0]=${WORK_DIR}/${RUN_DATE_FILE}"_Lista_Files_Rep_Dir0.log"			# <-----  <MODIFICABLE>

  LISTA_FILES_REP[1]=${WORK_DIR}/${RUN_DATE_FILE}"_Lista_Files_Rep_Dir1.log"			# <-----  <MODIFICABLE>

PATRON_DIR_MINIAT_CGATE=983db6   				# <-----  <MODIFICABLE>

NOM_CEL=Caso_Pru_1_5

DIR_FILES_COPIADOS_DEL_CEL=/home/badubko/Work_Dir_Ordena_Fotos_Cel/Para_Caso_Pru_1_5

ESTR_TEMP="${WORK_DIR}/${NOM_CEL}/Estr_Temp_${NOM_CEL}"

LISTA_FILES_ESTR_TEMP=$WORK_DIR/$NOM_CEL/Lista_Files_Estr_Temp_$NOM_CEL

SUB_DIR_NO_COPIAR="Sub_Dir_NO_Copiar"						# <-----  <MODIFICABLE>

LISTA_FILES_NO_COPIAR=${WORK_DIR}"/${SUB_DIR_NO_COPIAR}/Lista_Files_No_Copiar_Gral"

ARCHIVO_LOG=${WORK_DIR}/${NOM_CEL}/${RUN_DATE_FILE}'_Arch_Log_'${NOM_CEL}'.log'

WORK_SCRIPT_VID=${WORK_DIR}/${NOM_CEL}/${RUN_DATE_FILE}'_W-S_VID_'${NOM_CEL}'.sh'

LISTAR_MODULOS="TRUE"									# <-----  <MODIFICABLE>

GENERAR_REP_T_PARC="TRUE" 							#<-----  <MODIFICABLE>

REPORTA_HALLADO_EN_NC="TRUE" 						#<-----  <MODIFICABLE>

REPORTE_DEL_ZIP="FALSE"

}
#----------------------------------------------------------------


